#pragma once

#include <sqlite3.h>
#include <iostream>
#include <string>

namespace stdrave {

enum class APIKeyFlags : uint32_t
{
    APIKey_manual = 1, //It means is manually generated by GR, no user payment for this key
};

struct AccountState
{
    float       m_lastStep;
    float       m_consumed;
    uint32_t    m_limit;
    
    APIKeyFlags m_keyFlags;
    std::string m_apiKey;
    
    AccountState():
    m_lastStep(.0f),
    m_consumed(.0f),
    m_limit(100) //TODO: Fake for now!
    {
        
    }
};

bool createTable(sqlite3* db);

bool storeValues(sqlite3* db, const std::string& apiKey, float creditsConsumed, uint32_t creditsLimit, APIKeyFlags keyFlags);
bool getValues(sqlite3* db, const std::string& apiKey, float& creditsConsumed, uint32_t& creditsLimit, APIKeyFlags& keyFlags);

bool consumeCredits(sqlite3* db, const std::string& apiKey, float credits);
std::string isAPIKeyValid(sqlite3* db, const std::string& apiKey);

bool startDatabse();
bool shutdownDatabase();

}
