#include "Peer.h"
#include "Utils.h"

using namespace utility;
using namespace web;
using namespace http;

namespace stdrave {

Peer::Peer()
{

}

std::string Peer::getHeader()
{
    std::stringstream scout;
    scout << MERCH_PRODUCT_NAME << " - a personal educational project." << std::endl;
    scout << "Does not represent a commercial product, prototype, or concept!" << std::endl;
    scout << std::endl << "Created by " << AUTHOR_NAME << ", © 2025" << std::endl;
    scout << AUTHOR_CONTACTS << std::endl;
    
    return scout.str();
}

std::string Peer::getDisclamer()
{
    std::string disclamer;
    disclamer += "This project has been auto-generated by a machine learning models for educational purposes only.\n";
    disclamer += "Use with caution – the compiled code may contain defects, security vulnerabilities, or other issues.\n";
    disclamer += "Do not integrate this file into production or sensitive code bases without thorough review and testing!\n";
    return disclamer;
}

std::string Peer::getProductDescription()
{
    std::string description;
    description += MERCH_PRODUCT_NAME;
    description += " is a long-horizon AI programmer that, given a concise input project description and test cases, can synthesize complex algorithms.\n\n";
    description += "The programmer uses specialized chain-of-thought to decompose the problem, reason about each step,\n";
    description += "ensure consistent functional and data flow and generate syntactically correct and … working code!\n";
    description += "Embodied in a high-bandwidth development environment that provides a constant stream of ground-truth data,\nthe ";
    description += MERCH_PRODUCT_NAME;
    description += " accumulates knowledge during inference to maintain a reliable long trajectory.\n\n";
    
    return description;
}

int Peer::init(int argc, char* argv[])
{
    for (int i = 1; i < argc; ++i)
    {
        if (std::string(argv[i]) == "-llmpx")
        {
            m_llmProxyIP += argv[i + 1];
        }
        else if (std::string(argv[i]) == "-cpx")
        {
            m_chatProxyIP += argv[i + 1];
        }
        else if (std::string(argv[i]) == "-env")
        {
            m_environmentDirectory = argv[i+1];
            std::cout << "Environment directory " << m_environmentDirectory << std::endl;
        }
        else if(std::string(argv[i]) == "-llmDir")
        {
            std::string providerAndModelArg = argv[i+1];
            m_llmDirector = splitByFirstOccurence(providerAndModelArg, '/');
        }
        else if(std::string(argv[i]) == "-llmExp")
        {
            std::string providerAndModelArg = argv[i+1];
            m_llmExpert = splitByFirstOccurence(providerAndModelArg, '/');
        }
        else if(std::string(argv[i]) == "-llmDev")
        {
            std::string providerAndModelArg = argv[i+1];
            m_llmDeveloper = splitByFirstOccurence(providerAndModelArg, '/');
        }
    }
    
    if(!m_environmentDirectory.empty())
    {
        std::string llmRegistryPath = m_environmentDirectory + "/LLRegistry.json";
        
        std::ifstream file(llmRegistryPath);
        std::string str((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());

        auto ustr = conversions::to_string_t(str);
        json::value llmRegistryJson = json::value::parse(ustr);
        m_llms.from_json(llmRegistryJson);
    }
    
    for(auto& llm : m_llms.llms)
    {
        llm->findRolesMask();
    }

    return 0;
}

std::shared_ptr<LLMConfig> Peer::findLLM(const std::string& provider, const std::string& model)
{
    for(auto llm : m_llms.llms)
    {
        if(llm->provider == provider && llm->model == model)
        {
            return llm;
        }
    }
    
    return nullptr;
}

void Peer::sendRequest(http_client& client, const json::value& requestBody, json::value& responseBody)
{
    try {
        client.request(methods::POST, U(""), requestBody).then([&responseBody](http_response response) -> pplx::task<json::value>
            {
                if (response.status_code() == status_codes::OK)
                {
                    return response.extract_json(); // Continue the chain if OK
                }
                else {
                    // Create an error message that includes the response status code
                    std::string errorMessage = "Failed to get response. Error code: " + std::to_string(response.status_code());

                    // If not OK, stop the chain and pass the error forward
                    return pplx::task_from_exception<json::value>(std::runtime_error(errorMessage));
                }
            }).then([&responseBody](pplx::task<json::value> previousTask)
                {
                    try {
                        // Try to get the result, which could throw the exception from the previous task
                        responseBody = previousTask.get();
                    } catch (const std::exception& e) {
                        // Handle or log the error as needed
                        std::cerr << "Exception caught: " << e.what() << std::endl;
                        // Optionally, re-throw or handle the exception as appropriate
                    }
                }).wait(); // Wait on the final task, after handling exceptions
    } catch (const std::exception& e) {
        // This catches exceptions thrown from the initial request or wait()
        std::cerr << "Exception caught in sendRequest: " << e.what() << std::endl;
        // Handle the exception, maybe set an error in responseBody, or re-throw as needed
    }
}

}
